# -*- coding: utf-8 -*-
"""ETL project_data_aquisition_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GOx5MyZYV33I0AYNY7gXnklXH2GmROAn
"""

!pip install requests bs4 selenium webdriver-manager Google-search-results -q google-colab-selenium pyvis

import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time
import networkx as nx
import matplotlib.pyplot as plt
from serpapi import GoogleSearch
import  google_colab_selenium as gs
import seaborn as sns
import pyvis

import requests
url="https://www.ebay.com/b/Cell-Phones-Smartphones/9355/bn_320094"
headers={ "User-Agent" : "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36"}
r=requests.get(url, headers=headers)
print(r)

results=[]
soup=BeautifulSoup(r.content,"html5lib")
items=soup.find_all("div",class_='brwrvr__item-card__wrapper')
for item in items:
  title_found=item.find('h3',class_='textual-display bsig__title__text')
  title_element=title_found.text.strip() if title_found else 'N/A'
  price_found=item.find('span',class_='textual-display bsig__price bsig__price--displayprice')
  price_element=price_found.text.strip() if price_found else 'N/A'
  if title_element!='N/A' and price_element!='N/A':
    results.append({"product":title_element,"price":price_element})
results

df=pd.DataFrame(results)
df.to_csv('ebay_smart phones_by_bs4.csv',index=False)

from serpapi import GoogleSearch

params={
    "engine":"google_shopping",
    "q":"Smart phones ",
    "api_key":"#put your api key here"
}
search=GoogleSearch(params)

products=search.get_dict()
products

product_result=products['shopping_results']
print(product_result)
print(len(product_result))

for product in product_result:
    print(product.get('position'),":",product.get('title'),":",product.get('price'))

df=pd.DataFrame(product_result)
df.to_csv('Smartphones_by_serpapi.csv',index=True)

!wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!apt install -y ./google-chrome-stable_current_amd64.deb
!pip install -q selenium webdriver-manager

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

options = webdriver.ChromeOptions()
options.add_argument('--headless=new')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
options.add_argument('--disable-gpu')
options.add_argument('--window-size=1920,1080')

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)

driver.get("https://www.ebay.com/b/Cell-Phones-Smartphones/9355/bn_320094")
time.sleep(10)

products=[]
items=driver.find_elements(By.CLASS_NAME,'brwrvr__item-card__wrapper')
for item in items:
  title_element = item.find_elements(
    By.CSS_SELECTOR, ".textual-display.bsig__title__text"
)
  title=title_element[0].text.strip() if title_element else 'N/A'
  price_element = item.find_elements(
    By.CSS_SELECTOR, ".textual-display.bsig__price.bsig__price--displayprice"
)
  price=price_element[0].text.strip()if price_element else 'N/A'
  if title!='N/A'and price!='N/A':
    products.append({"product":title,"price":price})
print(f"found{len(products)}")
for i,product in enumerate(products):
  print(f"{i+1}:{product['product']}-{product['price']}")
df=pd.DataFrame(products)
df.to_csv('ebay.smartPhones.selenium.csv',index=False)
driver.quit()

import pandas as pd
df_bs4 = pd.DataFrame(results)
df_bs4['Source'] = 'bs4'
df_serp = pd.DataFrame(product_result)
df_serp['Source'] = 'serpapi'
df_sel = pd.read_csv('ebay.smartPhones.selenium.csv')
df_sel['Source'] = 'selenium'
df_all = pd.concat([df_bs4, df_serp, df_sel], ignore_index=True)
df_all['item_name'] = df_all.get('product', pd.Series()).fillna(df_all.get('title', ''))
df_all['item_name'] = df_all['item_name'].astype(str).str.strip()
df_all = df_all[~df_all['item_name'].str.contains('shop on ebay', case=False, na=False)]
df_all = df_all[df_all['item_name'] != '']
def clean_price(p):
    if isinstance(p, dict):
        return p.get('extracted', None)
    try:
        p = str(p)
        p = p.replace('$', '').replace(',', '')
        return float(p.split()[0])
    except:
        return None
df_all['price_cleaned'] = df_all['price'].apply(clean_price)
df_all = df_all.dropna(subset=['price_cleaned'])
df_all = df_all[df_all['price_cleaned'] > 5]
df_all = df_all.dropna(axis=1, how='all')
df_all = df_all[['item_name', 'price_cleaned', 'Source']]
df_all.to_csv('prices_after_clean.csv', index=False)
print(df_all.head())

import networkx as nx
import matplotlib.pyplot as plt
G_bs4 = nx.Graph()
for name in df_all[df_all['Source'] == 'bs4']['item_name']:
    G_bs4.add_edge('bs4', name)
plt.figure(figsize=(20, 10))
nx.draw(G_bs4, with_labels=True, node_color='skyblue', font_size=8, node_size=5000, edge_color='gray')
plt.title("bs4 networkx without normalization")
plt.show()

import networkx as nx
import matplotlib.pyplot as plt
G_api = nx.Graph()
for name in df_all[df_all['Source'] == 'serpapi']['item_name']:
    G_api.add_edge('api', name)
plt.figure(figsize=(20, 10))
nx.draw(G_api, with_labels=True, node_color='red', font_size=8, node_size=5000, edge_color='gray')
plt.title("serpapi networkx without normalization")
plt.show()

import networkx as nx
import matplotlib.pyplot as plt
G_selenium = nx.Graph()
for name in df_all[df_all['Source'] == 'selenium']['item_name']:
    G_selenium.add_edge('selenium', name)
plt.figure(figsize=(20, 10))
nx.draw(G_selenium, with_labels=True, node_color='green', font_size=8, node_size=5000, edge_color='gray')
plt.title("selenium networkx without normalization")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
filtered_df_all = df_all[df_all['price_cleaned'] > 0]
summary_stats = filtered_df_all.groupby('Source')['price_cleaned'].agg(['count', 'mean', 'max', 'min'])
summary_stats.columns = ['count', 'avg price', 'Max price', 'min price']
plt.figure(figsize=(20, 10))
sns.heatmap(summary_stats, annot=True, cmap="Reds", fmt='.2f', linewidths=1)
plt.title("Summary Statistics of mobile Prices by Source (Excluding Zero Prices)")
plt.show()

from plotly.subplots import make_subplots
import plotly.graph_objects as go
sources = df_all['Source'].unique()
fig = make_subplots(
    rows=1,
    cols=len(sources),
    subplot_titles=sources
)
for i, src in enumerate(sources):
    df_src = df_all[df_all['Source'] == src]
    fig.add_trace(
        go.Histogram(x=df_src['price_cleaned'], name=src),
        row=1,
        col=i+1
    )
fig.update_layout(title="Price Comparison per Source")

fig.show()

import plotly.express as px
df_all['index'] = df_all.index
df_all['rank'] = df_all['price_cleaned'].rank()
fig = px.scatter_3d(
    df_all,
    x='index',
    y='price_cleaned',
    z='rank',
    color='Source',
    hover_name='item_name',
    title="3D Comparison"
)

fig.show()

import plotly.express as px
df_all['name_length'] = df_all['item_name'].apply(len)
df_all['rank'] = df_all['price_cleaned'].rank()
fig = px.scatter_3d(
    df_all,
    x='price_cleaned',
    y='name_length',
    z='rank',
    color='Source',
    hover_name='item_name',
    title="3D Analysis: Price vs Name Complexity vs Rank"
)

fig.show()

import plotly.express as px
fig = px.box(
    df_all,
    x='Source',
    y='price_cleaned',
    title="Outliers Detection per Source"
)
fig.show()

print(df_all.groupby('Source')['price_cleaned'].describe())

from sklearn.cluster import KMeans
X = df_all[['price_cleaned']]
kmeans = KMeans(n_clusters=3)
df_all['cluster'] = kmeans.fit_predict(X)
fig = px.scatter_3d(
    df_all,
    x='price_cleaned',
    y='name_length',
    z='cluster',
    color='cluster',
    hover_name='item_name',
    title="3D Clustering of Products"
)

fig.show()

df_all['item_name'] = df_all['item_name'].astype(str).str.lower()
df_all['brand'] = df_all['item_name'].str.extract(
    r'(iphone|samsung|huawei|xiaomi|apple|galaxy)',
    expand=False
)

print(df_all['brand'].value_counts())

import plotly.express as px
fig = px.box(
    df_all,
    x='brand',
    y='price_cleaned',
    title="Price Distribution per Brand"
)
fig.show()

df_all['brand'] = df_all['item_name'].str.lower()
brands = ['iphone', 'samsung']
for b in brands:
    df_brand = df_all[df_all['brand'].str.contains(b, na=False)].copy()
    df_brand = df_brand.sort_values(by='price_cleaned', ascending=False)
    df_brand.to_csv(f"{b}_products.csv", index=False)
    print(f"{b} saved:", len(df_brand))

import networkx as nx
import matplotlib.pyplot as plt
df_sample = df_all.sample(n=60, random_state=42)
G = nx.Graph()
for index, row in df_sample.iterrows():
    G.add_edge(row['Source'], row['item_name'])
sources = df_all['Source'].unique()
items = [node for node in G.nodes() if node not in sources]
plt.figure(figsize=(24, 16))
pos = nx.spring_layout(G, k=0.9, iterations=50)
nx.draw_networkx_nodes(G, pos, nodelist=[s for s in sources if s in G.nodes()], node_color='red', node_size=6000, alpha=0.9, edgecolors='black', linewidths=2)
nx.draw_networkx_nodes(G, pos, nodelist=items, node_color='skyblue', node_size=1000, alpha=0.8, edgecolors='gray')
nx.draw_networkx_edges(G, pos, edge_color='gray', alpha=0.5, width=1.2)
source_labels = {source: str(source) for source in sources if source in G.nodes()}
nx.draw_networkx_labels(G, pos, labels=source_labels, font_size=18, font_weight='bold', font_color='white')
item_labels = {item: str(item)[:15] + '..' if len(str(item)) > 15 else str(item) for item in items}
nx.draw_networkx_labels(G, pos, labels=item_labels, font_size=10, font_weight='bold', font_color='black')
plt.title("Network: Sources and Products (With Names)", fontsize=22)
plt.axis('off')
plt.show()

!pip install pyvis

import ipywidgets as widgets
from IPython.display import display, clear_output
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import re

def extract_storage(name):
    match = re.search(r'(\d+\s*(?:GB|TB|gb|tb))', str(name))
    return match.group(1).replace(" ", "").lower() if match else "unknown"

df_all['storage'] = df_all['item_name'].apply(extract_storage)

le_source = LabelEncoder()
le_brand = LabelEncoder()
le_storage = LabelEncoder()

df_ml = df_all.copy()
df_ml['source_enc'] = le_source.fit_transform(df_ml['Source'])
df_ml['brand_enc'] = le_brand.fit_transform(df_ml['brand'].fillna('unknown'))
df_ml['storage_enc'] = le_storage.fit_transform(df_ml['storage'])

X = df_ml[['source_enc', 'brand_enc', 'storage_enc']]
y = df_ml['price_cleaned']

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X, y)

output = widgets.Output()

brand_dd = widgets.Dropdown(
    options=sorted(df_ml['brand'].fillna('unknown').unique()),
    description='Brand:',
    style={'description_width': 'initial'}
)

source_dd = widgets.Dropdown(
    options=df_ml['Source'].unique(),
    description='Source:',
    style={'description_width': 'initial'}
)

storage_dd = widgets.Dropdown(
    options=sorted(df_ml['storage'].unique()),
    description='Storage:',
    style={'description_width': 'initial'}
)

predict_btn = widgets.Button(
    description='Predict Price',
    button_style='success',
    layout=widgets.Layout(width='200px')
)

def on_predict_clicked(b):
    with output:
        clear_output()
        try:
            brand_idx = le_brand.transform([brand_dd.value])[0]
            source_idx = le_source.transform([source_dd.value])[0]
            storage_idx = le_storage.transform([storage_dd.value])[0]

            prediction = model.predict([[source_idx, brand_idx, storage_idx]])

            print(f" Analysis complete:")
            print(f" Predicted Price: {prediction[0]:,.2f} $")
            print(f" Based on Storage: {storage_dd.value}")
        except Exception as e:
            print(f"Error during prediction: {e}")

predict_btn.on_click(on_predict_clicked)

header = widgets.HTML("<h2> Price Predictor (Storage-Based Model)</h2>")
ui = widgets.VBox([header, brand_dd, source_dd, storage_dd, predict_btn])
display(ui, output)

import ipywidgets as widgets
from IPython.display import display, clear_output
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import re
import plotly.graph_objects as go
df_ml = df_all.copy()
df_ml['brand'] = df_ml['brand'].fillna('unknown')
def get_storage(text):
    m = re.search(r'(\d+\s*(?:GB|TB|gb|tb))', str(text))
    if m:
        return m.group(1).replace(" ", "").lower()
    return "unknown"
df_ml['storage'] = df_ml['item_name'].apply(get_storage)
le_src = LabelEncoder()
df_ml['Source_enc'] = le_src.fit_transform(df_ml['Source'])
le_brnd = LabelEncoder()
df_ml['brand_enc'] = le_brnd.fit_transform(df_ml['brand'])
le_strg = LabelEncoder()
df_ml['storage_enc'] = le_strg.fit_transform(df_ml['storage'])
X = df_ml[['Source_enc', 'brand_enc', 'storage_enc']]
y = df_ml['price_cleaned']
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X, y)
out = widgets.Output()
b_drop = widgets.Dropdown(options=sorted(df_ml['brand'].unique()), description='Brand:')
s_drop = widgets.Dropdown(options=df_ml['Source'].unique(), description='Source:')
st_drop = widgets.Dropdown(options=sorted(df_ml['storage'].unique()), description='Storage:')
price_in = widgets.FloatText(value=0.0, description='Found Price:')
btn = widgets.Button(description='Analyze Deal', button_style='success')
def check_deal(b):
    with out:
        clear_output()
        try:
            b_val = le_brnd.transform([b_drop.value])[0]
            s_val = le_src.transform([s_drop.value])[0]
            st_val = le_strg.transform([st_drop.value])[0]
            pred = model.predict([[s_val, b_val, st_val]])[0]
            my_price = price_in.value
            print("Analysis complete:")
            print(f"Fair Market Price: {pred:,.2f} $")
            if my_price > 0:
                if my_price < pred:
                    status = "GREAT DEAL (Below Market Value)"
                elif my_price > pred:
                    status = "OVERPRICED (Above Market Value)"
                else:
                    status = "FAIR PRICE"
                print(f"Your Found Price: {my_price:,.2f} $")
                print(f"Deal Status: {status}")
                gauge = go.Figure(go.Indicator(
                    mode="gauge+number+delta",
                    value=my_price,
                    domain={'x': [0, 1], 'y': [0, 1]},
                    title={'text': "Deal Analyzer", 'font': {'size': 20}},
                    delta={'reference': pred, 'increasing': {'color': "red"}, 'decreasing': {'color': "green"}},
                    gauge={
                        'axis': {'range': [None, pred * 1.5], 'tickwidth': 1, 'tickcolor': "darkblue"},
                        'bar': {'color': "black"},
                        'bgcolor': "white",
                        'borderwidth': 2,
                        'bordercolor': "gray",
                        'steps': [
                            {'range': [0, pred * 0.9], 'color': "lightgreen"},
                            {'range': [pred * 0.9, pred * 1.1], 'color': "lightyellow"},
                            {'range': [pred * 1.1, pred * 1.5], 'color': "salmon"}],
                        'threshold': {'line': {'color': "blue", 'width': 4}, 'thickness': 0.75, 'value': pred}}))
                gauge.show()
            else:
                print("Enter a 'Found Price' above 0 to see the interactive deal gauge.")
        except Exception as e:
            print(f"Error: {e}")

btn.on_click(check_deal)

hdr = widgets.HTML("<h2>Smart Deal Analyzer</h2>")
display(widgets.VBox([hdr, b_drop, s_drop, st_drop, price_in, btn]), out)

import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd
brands_list = ['All'] + sorted(df_all['brand'].fillna('unknown').unique().tolist())
brand_filter = widgets.Dropdown(options=brands_list, description='Filter Brand:')
btn_data = widgets.Button(description='View Data', button_style='info')
btn_nulls = widgets.Button(description='Check Nulls', button_style='warning')
out_display = widgets.Output()
def view_data_clicked(b):
    with out_display:
        clear_output()
        if brand_filter.value == 'All':
            df_view = df_all.head(10)
        else:
            df_view = df_all[df_all['brand'] == brand_filter.value].head(10)
        print(f"Showing sample data for: {brand_filter.value}")
        display(df_view)
def check_nulls_clicked(b):
    with out_display:
        clear_output()
        print("Missing Values in the Dataset:")
        display(pd.DataFrame(df_all.isnull().sum(), columns=['Missing Count']))

btn_data.on_click(view_data_clicked)
btn_nulls.on_click(check_nulls_clicked)
controls = widgets.HBox([brand_filter, btn_data, btn_nulls])
header = widgets.HTML("<h2>Data Exploration & Cleaning Dashboard</h2>")

display(widgets.VBox([header, controls, out_display]))

import plotly.io as pio
pio.renderers.default = 'colab'
import plotly.express as px
brand_data = df_all['brand'].value_counts().reset_index()
brand_data.columns = ['Brand Name', 'Count']
fig1 = px.bar(brand_data, x='Brand Name', y='Count', title='Handsets by Brand')
fig1.show()

import plotly.express as px
top_brands = df_all['brand'].value_counts().nlargest(6)
brand_counts = df_all['brand'].value_counts().reset_index()
brand_counts.columns = ['brand', 'count']
fig = px.pie(brand_counts,
             values='count',
             names='brand',

             hole=0.6)
fig.update_traces(textinfo='percent+label')
fig.show()

import matplotlib.pyplot as plt
brand_data = df_all['brand'].value_counts()
plt.figure(figsize=(30, 30))
plt.pie(brand_data,
        labels=brand_data.index,

        startangle=140,
        colors=plt.cm.Paired.colors)
plt.title('Market Share by Brand')
plt.axis('equal')
plt.show()
